
SELECT *
FROM Student4
LEFT OUTER JOIN Pet
ON S_ID = P_OwnerID
WHERE P_Name IS NULL;

SELECT *
FROM Student4
RIGHT OUTER JOIN Pet
ON S_ID = P_OwnerID
WHERE S_Name IS NULL;

SELECT *
FROM Student4
FULL OUTER JOIN Pet
ON S_ID = P_OwnerID
WHERE S_Name IS NULL
OR P_Name IS NULL;